export default {
  TURTLE: 'Turtle',
  FLOWERS: 'Flowers',
  BRUSH: 'Brush',
  BASKET: 'Basket',
  CHICK: 'Chick',
  EGG: 'Egg',
  PALETTE: 'Palette',
  MEDALLION: 'Medallion',
  BOOK: 'Book',
  BUCKET: 'Bucket',
  UNICORN: 'Unicorn',
  PLANE: 'Plane',
  SHOVEL: 'Shovel',
  CANDLE: 'Candle',
  CLOCK: 'Clock',
  ENVELOPE: 'Envelope',
  BUTTERFLY: 'Butterfly',
  COIN: 'Coin',
  FAIRY: 'Little Fairy',
  RAINBOW: 'Rainbow',
  TOOTH: 'Tooth',
  MEMORY_BOX: 'Memory box',
  TOOTHBRUSH: 'Toothbrush',
  CLOUD: 'Cloud',
  LOCK: 'Lock',
  BERET: 'Beret',
  FIREWORKS: 'Fireworks',
  STICK: 'Stick',
  ICE: 'Ice',
  SNOWBALL: 'Snowball',
  MOON: 'Moon',
  SNOWFLAKE: 'Snowflake',
  SKATES: 'Skates',
  ELF: 'Elf',
  ROBOT: 'Robot',
  LOLLIPOP: 'Lollipop',
  MATRYOSHKA: 'Matryoshka',
  SOCK: 'Sock',
  SNOWMAN: 'Snowman',
  STAR: 'Star',
  GINGERBREAD_MAN: 'Gingerbread',
  SANTA_HAT: 'Santa hat',
  YETI: 'Yeti',
  EARTH: 'Earth',
  WREATH: 'Wreath',
  NIGHTMARE: 'Nightmare',
  SANTA: 'Santa',
  BOOGEYMAN: 'Boogeyman',
  JACK_FROST: 'Jack Frost',
  EASTER_BUNNY: 'Easter Bunny',
  SANDMAN: 'Sandman',
  DEER: 'Deer',
  TOOTH_FAIRY: 'Tooth Fairy',
};
