export default {
  TURTLE: 'Черепаха',
  FLOWERS: 'Цветы',
  BRUSH: 'Кисточка',
  BASKET: 'Корзина',
  CHICK: 'Цыпленок',
  EGG: 'Яйцо',
  PALETTE: 'Палитра',
  MEDALLION: 'Медальон',
  BOOK: 'Книга',
  BUCKET: 'Ведро',
  UNICORN: 'Единорог',
  PLANE: 'Самолет',
  SHOVEL: 'Лопата',
  CANDLE: 'Свеча',
  CLOCK: 'Часы',
  ENVELOPE: 'Конверт',
  BUTTERFLY: 'Бабочка',
  COIN: 'Монета',
  FAIRY: 'Феечка',
  RAINBOW: 'Радуга',
  TOOTH: 'Зуб',
  MEMORY_BOX: 'Ящик памяти',
  TOOTHBRUSH: 'Зубная щетка',
  CLOUD: 'Облако',
  LOCK: 'Замок',
  BERET: 'Берет',
  FIREWORKS: 'Фейерверк',
  STICK: 'Посох',
  ICE: 'Лед',
  SNOWBALL: 'Снежок',
  MOON: 'Луна',
  SNOWFLAKE: 'Снежинка',
  SKATES: 'Коньки',
  ELF: 'Эльф',
  ROBOT: 'Робот',
  LOLLIPOP: 'Чупа-чупс',
  MATRYOSHKA: 'Матрешка',
  SOCK: 'Носок',
  SNOWMAN: 'Снеговик',
  STAR: 'Звезда',
  GINGERBREAD_MAN: 'Пряник',
  SANTA_HAT: 'Шляпа Санты',
  YETI: 'Йети',
  EARTH: 'Земля',
  WREATH: 'Венок',
  NIGHTMARE: 'Кошмар',
  SANTA: 'Санта',
  BOOGEYMAN: 'Кромешник',
  JACK_FROST: 'Ледяной Джек',
  EASTER_BUNNY: 'Пасх. кролик',
  SANDMAN: 'Песочник',
  DEER: 'Олень',
  TOOTH_FAIRY: 'Зубная фея',
};
