export default {
  TURTLE: 'Чарапаха',
  FLOWERS: 'Кветка',
  BRUSH: 'Шчотка',
  BASKET: 'Кошык',
  CHICK: 'Кураня',
  EGG: 'Яйка',
  PALETTE: 'Палітра',
  MEDALLION: 'Медальён',
  BOOK: 'Кніга',
  BUCKET: 'Вядро',
  UNICORN: 'Аднарог',
  PLANE: 'Самалёт',
  SHOVEL: 'Рыдлёўка',
  CANDLE: 'Свечка',
  CLOCK: 'Гадзіннік',
  ENVELOPE: 'Канверт',
  BUTTERFLY: 'Матылек',
  COIN: 'Манета',
  FAIRY: 'Маленькая фея',
  RAINBOW: 'Вясёлка',
  TOOTH: 'Зуб',
  MEMORY_BOX: 'Скрынка памяці',
  TOOTHBRUSH: 'Зубная шчотка',
  CLOUD: 'Воблака',
  LOCK: 'Замок',
  BERET: 'Бярэт',
  FIREWORKS: 'Феерверк',
  STICK: 'Посах',
  ICE: 'Лёд',
  SNOWBALL: 'Сняжок',
  MOON: 'Месяц',
  SNOWFLAKE: 'Сняжынка',
  SKATES: 'Канькі',
  ELF: 'Эльф',
  ROBOT: 'Робат',
  LOLLIPOP: 'Лядзяш',
  MATRYOSHKA: 'Матрошка',
  SOCK: 'Шкарпэтка',
  SNOWMAN: 'Снегавік',
  STAR: 'Зорка',
  GINGERBREAD_MAN: 'Пернік',
  SANTA_HAT: 'Капялюш Санты',
  YETI: 'Еці',
  EARTH: 'Зямля',
  WREATH: 'Вянок',
  NIGHTMARE: 'Кашмар',
  SANTA: 'Санта',
  BOOGEYMAN: 'Бугимен',
  JACK_FROST: 'Джэк Фрост',
  EASTER_BUNNY: 'Велікодны трусік',
  SANDMAN: 'Пясочнік',
  DEER: 'Алень',
  TOOTH_FAIRY: 'Зубная фея',
};
