export default {
  NEW_GAME: 'New game',
  CONTINUE: 'Continue',
  OPTIONS: 'Options',
  EXIT: 'Exit game',
  STARTUP_QUERY_TITLE: 'TURN ON SOUNDS?',
  ACCEPT: 'Yes',
  DECLINE: 'No',
  OPTIONS_TITLE: 'OPTIONS',
  OPTIONS_CHILD_MODE: 'Child mode',
  OPTIONS_FULLSCREEN: 'Fullscreen (F11)',
  LOADING: 'Loading',
  PAUSE: 'PAUSE',
  HINT: 'HINT',
  RESTART: 'Restart',
  MENU: 'Main menu',
  OPTIONS: 'Options',
  LOAD: 'Load game',
  LEVEL_WON_TITLE: 'You won!',
  NEXT_LEVEL: 'Next level',
}