export default {
  NEW_GAME: 'Новая игра',
  CONTINUE: 'Продолжить',
  OPTIONS: 'Настройки',
  EXIT: 'Выход',
  STARTUP_QUERY_TITLE: 'ВКЛЮЧИТЬ ЗВУК?',
  ACCEPT: 'Да',
  DECLINE: 'Нет',
  OPTIONS_TITLE: 'НАСТРОЙКИ',
  OPTIONS_CHILD_MODE: 'Детский режим',
  OPTIONS_FULLSCREEN: 'Во весь экран (F11)',
  LOADING: 'Загрузка',
  PAUSE: 'Пауза',
  BACK_TO_MENU: 'Обратно в меню',
  PAUSE_MESSAGE: 'Игра приостановлена!',
  LOST_MESSAGE: 'Игра закончена! Время вышло!',
  LOST_MESSAGE_MOVES: 'Игра закончена! Закончились ходы!',
  HINT: 'Подсказка',
  RESTART: 'Начать заново',
  MENU: 'В главное меню',
  LEVEL_WON_TITLE: 'Вы победили!',
  NEXT_LEVEL: 'К карте',
  LANGUAGE: 'Язык',
  LANG_EN: 'Английский',
  LANG_RU: 'Русский',
  LANG_BY: 'Белорусский',
  DISCLAIMER_TITLE: 'Дисклеймер',
  DEVELOPERS: 'Разработчики:',
  DEVELOPER1: 'Венцкуте Виктория',
  DEVELOPER2: 'Слапик Татьяна',
  MENTOR: 'Никита Левкович',
  MENTOR_TITLE: 'Ментор',
  DISCLAIMER_MESSAGE: '<h3>Хранители Снов</h3><p>Игра разработана в качестве выпускного таска для курсов <i>The Rolling Scopes JS/FE 2020Q3</i></p><p>Все права принадлежат создателям содержимого. Логотипы "Хранители Снов" и "Rise of the Guardians" принадлежат DreamWorks Animation SKG. © 2021.</p><p>Пожалуйста, посетите настройки для смены языка и других настроек</p>',
  DISCLAIMER_AGREE: 'Я прочитал. Погнали!',
};
