export default {
  NEW_GAME: 'Новая гульня',
  CONTINUE: 'Працягнуць',
  OPTIONS: 'Налады',
  EXIT: 'Выхад',
  STARTUP_QUERY_TITLE: 'ЎКЛЮЧЫЦЬ ГУКІ?',
  ACCEPT: 'Так',
  DECLINE: 'Не',
  OPTIONS_TITLE: 'НАЛАДЫ',
  OPTIONS_CHILD_MODE: 'Дзіцячы рэжым',
  OPTIONS_FULLSCREEN: 'Ва ўвесь экран (F11)',
  LOADING: 'Загрузка',
  PAUSE: 'Паўза',
  BACK_TO_MENU: 'Назад у меню',
  PAUSE_MESSAGE: 'Гульня прыпынена!',
  LOST_MESSAGE: 'Гульня скончана! Час выйшаў!',
  LOST_MESSAGE_MOVES: 'Гульня скончана! Скончыліся хады!',
  HINT: 'ПАДКАЗКА',
  RESTART: 'Пачаць нанова',
  MENU: 'У галоўнае меню',
  LEVEL_WON_TITLE: 'Вы перамаглі!',
  NEXT_LEVEL: 'Да карты',
  LANGUAGE: 'Мова',
  LANG_EN: 'Англійская',
  LANG_RU: 'Руская',
  LANG_BY: 'Беларуская',
  DISCLAIMER_TITLE: 'Дысклэймер',
  DEVELOPERS: 'Распрацоўшчыкі',
  DEVELOPER1: 'Венцкуце Вікторыя',
  DEVELOPER2: 'Слапік Таццяна',
  MENTOR: 'Мікіта Ляўковіч',
  MENTOR_TITLE: 'Ментар',
  DISCLAIMER_MESSAGE: '<h3>Захавальнікі Сноў</h3><p>Гульня распрацавана ў якасці выпускнога таска для курсаў <i>The Rolling Scopes JS/FE 2020Q3</i></p><p>Усе правы належаць стваральнікам змесціва. Лагатыпы "Захавальнікі сноў" і "Rise of the Guardians" належаць DreamWorks Animation SKG. © 2021.</p><p>Калі ласка, наведайце налады для змены мовы і іншых налад</p>',
  DISCLAIMER_AGREE: 'Я прачытаў. Пагналі!',
};
