export default {
  NEW_GAME: 'Новая игра',
  CONTINUE: 'Продолжить',
  OPTIONS: 'Настройки',
  EXIT: 'Выход',
  STARTUP_QUERY_TITLE: 'ВКЛЮЧИТЬ ЗВУК?',
  ACCEPT: 'Да',
  DECLINE: 'Нет',
  OPTIONS_TITLE: 'НАСТРОЙКИ',
  OPTIONS_CHILD_MODE: 'Детский режим',
  OPTIONS_FULLSCREEN: 'Во весь экран (F11)',
  LOADING: 'Загрузка',
  PAUSE: 'ПАУЗА',
  HINT: 'ПОДСКАЗКА',
  RESTART: 'Начать заново',
  MENU: 'В главное меню',
  LOAD: 'Загрузить игру',
  LEVEL_WON_TITLE: 'Вы победили!',
  NEXT_LEVEL: 'Следующий уровень',
  LANGUAGE: 'Язык',
  LANG_EN: 'Английский',
  LANG_RU: 'Русский',
  LANG_BY: 'Белорусский',
}