export default {
  NEW_GAME: 'Новая гульня',
  CONTINUE: 'Працягнуць',
  OPTIONS: 'Налады',
  EXIT: 'Выхад',
  STARTUP_QUERY_TITLE: 'ЎКЛЮЧЫЦЬ ГУКІ?',
  ACCEPT: 'Так',
  DECLINE: 'Не',
  OPTIONS_TITLE: 'НАЛАДЫ',
  OPTIONS_CHILD_MODE: 'Дзіцячы рэжым',
  OPTIONS_FULLSCREEN: 'Ва ўвесь экран (F11)',
  LOADING: 'Загрузка',
  PAUSE: 'Паўза',
  HINT: 'ПАДКАЗКА',
  RESTART: 'Пачаць нанова',
  MENU: 'У галоўнае меню',
  LOAD: 'Загрузіць гульню',
  LEVEL_WON_TITLE: 'Вы перамаглі!',
  NEXT_LEVEL: 'Наступны ўзровень',
  LANGUAGE: 'Мова',
  LANG_EN: 'Англійская',
  LANG_RU: 'Руская',
  LANG_BY: 'Беларуская',
}