export default {
  NEW_GAME: 'New game',
  CONTINUE: 'Continue',
  OPTIONS: 'Settings',
  EXIT: 'Exit game',
  STARTUP_QUERY_TITLE: 'TURN ON SOUNDS?',
  ACCEPT: 'Yes',
  DECLINE: 'No',
  OPTIONS_TITLE: 'SETTINGS',
  OPTIONS_CHILD_MODE: 'Child mode',
  OPTIONS_FULLSCREEN: 'Fullscreen (F11)',
  LOADING: 'Loading',
  PAUSE: 'Pause',
  BACK_TO_MENU: 'Back to menu',
  PAUSE_MESSAGE: 'Game is paused!',
  LOST_MESSAGE: 'Game away! Time is up!',
  LOST_MESSAGE_MOVES: 'Game away! Moves are up!',
  HINT: 'Hint',
  RESTART: 'Restart',
  MENU: 'Main menu',
  LEVEL_WON_TITLE: 'You won!',
  NEXT_LEVEL: 'To the map',
  LANGUAGE: 'Language',
  LANG_EN: 'English',
  LANG_RU: 'Russian',
  LANG_BY: 'Belarussian',
};
